# LPC Configuration
# Please read the https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta before you set up.
#
# Placeholders:
# {message} - the chat message
# {name} - the player's name
# {displayname} - the player's display name / nickname
# {prefix} - the player's highest priority prefix
# {suffix} - the player's highest priority suffix
# {prefixes} - the player's prefixes sorted by the highest priority
# {suffixes} - the player's suffixes sorted by the highest priority
# {username-color} - the player's or the group's username color
# {message-color} - the player's or the group's message color
#
# To reload the configuration, run '/lpc reload' command. Make sure you have the 'lpc.reload' permission assigned.
chat-format: "{prefix}{name}&r: {message}"

group-formats:
  default: "{prefix}{name}&r: {message}"
  admin: "{prefix}{name}&r: {message}"